version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing
  pre_build:
    commands:
      - echo move to src
      - cd express-minapp
      - echo Installing source NPM dependencies.
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo run build
      - npm build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - express-minapp/src/*
    - express-minapp/node_modules/dotenv/*
    - express-minapp/node_modules/express/*
    - express-minapp/node_modules/morgan/*
    - express-minapp/node_modules/cors/*
    - express-minapp/node_modules/mysql/*