version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing
  pre_build:
    commands:
      - echo move to src
      - cd express-minapp
      - echo Installing source NPM dependencies.
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo run dev
      - npm run dev
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - express-minapp/src/index.js
    - express-minapp/src/middlewares.js
    - express-minapp/node_modules/**/*